version: '3'

networks:
  laravel:

services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - './src:/var/www/html'
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    links:
      - db
    networks:
      - laravel

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    depends_on:
      - php
    networks:
      - laravel

  db:
    image: mysql:latest
    ports:
      - ${IP}:3300:3306
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${IP}:9090:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      PMA_ARBITRARY: 1
    links:
      - db:db
    networks:
      - laravel
